name: Escape Room Pipeline

on:
  push: { branches: rwq3/1 }

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - run: npm install
      - run: npm test
